name: M3U to TXT Converter

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: pip install requests

    - name: 运行转换脚本
      run: |
        python m3u_to_txt.py

    - name: 提交更改
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.txt
        git commit -m "自动更新频道列表" || echo "无变更需要提交"
        git push
